name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install nodeJS
      run: |
        sudo apt install nodejs
    - name: Install Dependencies
      run: npm install
    - name: Run npm unit tests
      run: npm run unit
    - name: Update coverage to coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
