name: Doc

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install nodeJS
      run: |
        sudo apt install nodejs
    - name: Install Dependencies
      run: npm install
    - name: Run the documentation
      run: npm run doc
    - name: Display current branch
      run: git branch
    - name: Commit to repository
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
        COMMIT_MSG: |
          <GITHUB-PIPELINE (automated msg): updating documentation files>
          skip-checks: true
      run: |
        git config user.email "batistadominique@hotmail.com"
        git config user.name "Terazus"
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git add 'source/components/*'
        git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push