name: Doc

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2-beta
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install Dependencies
      run: npm install
    - name: Run the documentation
      run: npm run doc ${GITHUB_REF##*/}
    - name: Commit changes
      uses: elstudio/actions-js-build/commit@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
